FROM nginx
MAINTAINER grant liuwei_sj@163.com

FROM alpine:latest
# Install Nginx
RUN apk --update add nginx
COPY . /usr/share/nginx/html
EXPOSE 80

# Start Nginx and keep it from running background
CMD ["nginx", "-g", "daemon off;"]
